server:
  port: 8080

client:
  base-url: "http://localhost:8080"   # จะถูก override ในเทสต์ให้ชี้ MockWebServer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    io.github.resilience4j: DEBUG
    io.github.resilience4j.spring6: DEBUG
    io.github.resilience4j.bulkhead: DEBUG
    io.github.resilience4j.ratelimiter: DEBUG